version: '3.9'

services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Warsaw"
    networks:
      - default
    depends_on:
      - cadvisor
      
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: unless-stopped
    environment:
      TZ: "Europe/Warsaw"
    networks:
      - default

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Warsaw"
    networks:
      - default

  calculator:
    image: ghcr.io/kpk666/web-calculator:latest
    ports:
      - 9095:80
    container_name: webcalculator
    hostname: webcalculator
    restart: unless-stopped
    environment:
      TZ: "Europe/Warsaw"  
    networks:
      - default

  alertmanager-bot:
    command:
      - --alertmanager.url=http://alertmanager:9093
      - --log.level=info
      - --store=bolt
      - --bolt.path=/data/bot.db
      - --telegram.admin=1336300466
      - --telegram.token=6110956366:AAEORGJkK1IgpyM63G3O1HREPtMQbxBuj58
    image: metalmatze/alertmanager-bot:0.4.3
    user: root
    ports:
      - 8082:8080
    container_name: alertmanager-bot
    hostname: alertmanager-bot
    environment:
      TZ: "Europe/Warsaw"
    restart: unless-stopped
    volumes:
      - ./data:/data
    networks:
      - default

  alertmanager:
    image: prom/alertmanager:v0.21.0
    user: root
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    container_name: alertmanager
    hostname: alertmanager
    environment:
      TZ: "Europe/Warsaw"
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/data'
    networks:
      - default

  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    hostname: blackbox
    ports:
      - 9115:9115
    restart: unless-stopped
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"
    volumes:
      - ./blackbox:/etc/blackbox
    environment:
      TZ: "Europe/Warsaw"
    networks:
      - default

  docker_exporter:
    image: prometheusnet/docker_exporter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: docker_exporter
    hostname: docker_exporter
    ports:
      - 9417:9417
    restart: unless-stopped
    environment:
      TZ: "Europe/Warsaw"
    networks:
      - default

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest # google/cadvisor:latest
    ports:
      - '8080:8080'
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    container_name: cadvisor
    hostname: cadvisor
    restart: unless-stopped
    environment:
      TZ: "Europe/Warsaw"
    networks:
      - default


networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16