scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
    - targets: 
      - 'node-exporter:9100'

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: 
      - 'localhost:9090'

  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:  
        - http://webcalculator:9095  
        - https://google.com     
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'blackbox_tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - webcalculator:9095
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115 

  - job_name: 'my_docker_metrics'
    static_configs:
    - targets: 
      - 'docker_exporter:9417'

  # - job_name: 'cadvisor' 
  #   static_configs:
  #     - targets: 
  #       - 'cadvisor:8086'

#  - job_name: "cadvisor"
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:8086']
#        labels:
#          alias: "cadvisor"

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8086']
        labels:
          alias: "cadvisor"

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

