jenkins:
  systemMessage: "<div style='font-size:160%; background-color: powerblue;'>This Jenkins configured was created for my diplom project</div>"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: github_ssh
              username: <your user>
              description: "SSH Github"
              privateKeySource:
                directEntry:
                  privateKey: ${github_ssh}
          - usernamePassword:
              id: github_PAT
              password: ${github_pat}
              scope: GLOBAL
              username: <your user>
          - string:
              scope: GLOBAL
              id: "accessKey"
              secret: "${accessKey}"
              description: "aws accessKey"
          - string:
              scope: GLOBAL
              id: "secretKey"
              secret: "${secretKey}"
              description: "aws secretKey"

security:
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "noHostKeyVerificationStrategy"

unclassified:
  location:
    url: ${JENKINS_URL}

jobs:
  - file: /var/jenkins_home/casc_configs/seedjob.groovy