name: CI calculator
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2        
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          npm init -y
          npm install htmlhint@latest eslint@latest eslint-plugin-html@latest
          echo "Dependencies are installed"
          
        
      - name: Testing HTML code
        run: |
          npx htmlhint '**/*.html'    
          echo "Testing of HTML is complited"
          
      - name: Testing java.scripts code
        run: |
          echo "Starting to launch java.script testing"
          echo "initialize init @eslint/config -y"
          npm init @eslint/config
          echo "Initizlization is complited"
          npx eslint 'Calculator/*.js' --fix --quiet 

    
  build:
    runs-on: self-hosted
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      working-directory: Calculator
      run: |
        docker build -t ghcr.io/kpk666/web-calculator:latest .
        docker push ghcr.io/kpk666/web-calculator:latest

  deploy:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: build
    runs-on: self-hosted    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy with Docker Compose
      working-directory: deploy
      run: |
        docker-compose pull
        docker-compose up -d --force-recreate

  
